version: "3.5"

volumes:
  postgres:

services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: rinha
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d rinha"]
      interval: 5s
      timeout: 5s
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.5GB"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api1:
    # image: insalubre/rinhabackend:latest
    build: .
    hostname: api1
    environment:
      PORT: 8080
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api2:
    # image: insalubre/rinhabackend:latest
    build: .
    hostname: api2
    environment:
      PORT: 8081
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  nginx:
    image: nginx
    hostname: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
